### PR TITLE
CHECK-165: BE: Rename update to add, adding a location route

### PR DESCRIPTION
**Pull request by JayJayAquino**
# Description

BE: Rename update to add, adding a location route
## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

just changed route name and all instances of updateLocation -> addLocation

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ChanM0 — CHANGES_REQUESTED** [review]
There is no Location Service Test

**Comment by JayJayAquino** [comment]
> There is no Location Service Test

Correct, however, adding one is out of scope for this task

I will make some tasks to create Service tests for routes that are missing them (there are multiple missing ones)

**Review by ChanM0 — CHANGES_REQUESTED** [review]
Redid this code

**Review by chippingcolt — APPROVED** [review]

**Review by chippingcolt — APPROVED** [review]

**Comment by JayJayAquino** [comment]
Closing, since this will be fixed in another branch

**Pull request closed without merging**
