### PR TITLE
CHECK-122: BE: Update Request Form of Register Admin to include state as a required param

### PR DESCRIPTION
**Pull request by JayJayAquino**
# Description

Add state param as required within rules and make a message response for this in the messages function. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by digitalsoba — APPROVED** [review]
coolio

**Review by ChanM0 — CHANGES_REQUESTED** [review]
Update test

**Review by chippingcolt — APPROVED** [review]
looks good ! see tests

**Comment by JayJayAquino** [comment]
> Update test

resolved in commit bf4fe68

**Review by ChanM0 — APPROVED** [review]
👍

**Pull request merged**
